// Generated by gencpp from file ee4308_turtle/EE4308MsgMotion.msg
// DO NOT EDIT!


#ifndef EE4308_TURTLE_MESSAGE_EE4308MSGMOTION_H
#define EE4308_TURTLE_MESSAGE_EE4308MSGMOTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ee4308_turtle
{
template <class ContainerAllocator>
struct EE4308MsgMotion_
{
  typedef EE4308MsgMotion_<ContainerAllocator> Type;

  EE4308MsgMotion_()
    : x(0.0)
    , y(0.0)
    , o(0.0)
    , v(0.0)
    , w(0.0)  {
    }
  EE4308MsgMotion_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , o(0.0)
    , v(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _o_type;
  _o_type o;

   typedef double _v_type;
  _v_type v;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> const> ConstPtr;

}; // struct EE4308MsgMotion_

typedef ::ee4308_turtle::EE4308MsgMotion_<std::allocator<void> > EE4308MsgMotion;

typedef boost::shared_ptr< ::ee4308_turtle::EE4308MsgMotion > EE4308MsgMotionPtr;
typedef boost::shared_ptr< ::ee4308_turtle::EE4308MsgMotion const> EE4308MsgMotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator1> & lhs, const ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.o == rhs.o &&
    lhs.v == rhs.v &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator1> & lhs, const ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ee4308_turtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e21c6318a89f0960f14408642fec1cea";
  }

  static const char* value(const ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe21c6318a89f0960ULL;
  static const uint64_t static_value2 = 0xf14408642fec1ceaULL;
};

template<class ContainerAllocator>
struct DataType< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee4308_turtle/EE4308MsgMotion";
  }

  static const char* value(const ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 o\n"
"float64 v\n"
"float64 w\n"
;
  }

  static const char* value(const ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.o);
      stream.next(m.v);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EE4308MsgMotion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ee4308_turtle::EE4308MsgMotion_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "o: ";
    Printer<double>::stream(s, indent + "  ", v.o);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EE4308_TURTLE_MESSAGE_EE4308MSGMOTION_H
