// Generated by gencpp from file ee4308_turtle/EE4308MsgMaster.msg
// DO NOT EDIT!


#ifndef EE4308_TURTLE_MESSAGE_EE4308MSGMASTER_H
#define EE4308_TURTLE_MESSAGE_EE4308MSGMASTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ee4308_turtle
{
template <class ContainerAllocator>
struct EE4308MsgMaster_
{
  typedef EE4308MsgMaster_<ContainerAllocator> Type;

  EE4308MsgMaster_()
    : seq(0)
    , stop(false)
    , target_x(0.0)
    , target_y(0.0)  {
    }
  EE4308MsgMaster_(const ContainerAllocator& _alloc)
    : seq(0)
    , stop(false)
    , target_x(0.0)
    , target_y(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _seq_type;
  _seq_type seq;

   typedef uint8_t _stop_type;
  _stop_type stop;

   typedef double _target_x_type;
  _target_x_type target_x;

   typedef double _target_y_type;
  _target_y_type target_y;





  typedef boost::shared_ptr< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> const> ConstPtr;

}; // struct EE4308MsgMaster_

typedef ::ee4308_turtle::EE4308MsgMaster_<std::allocator<void> > EE4308MsgMaster;

typedef boost::shared_ptr< ::ee4308_turtle::EE4308MsgMaster > EE4308MsgMasterPtr;
typedef boost::shared_ptr< ::ee4308_turtle::EE4308MsgMaster const> EE4308MsgMasterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator1> & lhs, const ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator2> & rhs)
{
  return lhs.seq == rhs.seq &&
    lhs.stop == rhs.stop &&
    lhs.target_x == rhs.target_x &&
    lhs.target_y == rhs.target_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator1> & lhs, const ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ee4308_turtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0effaf0c54ed4fd8e29b0800cfb2a4e3";
  }

  static const char* value(const ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0effaf0c54ed4fd8ULL;
  static const uint64_t static_value2 = 0xe29b0800cfb2a4e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee4308_turtle/EE4308MsgMaster";
  }

  static const char* value(const ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 seq\n"
"bool stop\n"
"float64 target_x\n"
"float64 target_y\n"
;
  }

  static const char* value(const ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seq);
      stream.next(m.stop);
      stream.next(m.target_x);
      stream.next(m.target_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EE4308MsgMaster_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ee4308_turtle::EE4308MsgMaster_<ContainerAllocator>& v)
  {
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop);
    s << indent << "target_x: ";
    Printer<double>::stream(s, indent + "  ", v.target_x);
    s << indent << "target_y: ";
    Printer<double>::stream(s, indent + "  ", v.target_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EE4308_TURTLE_MESSAGE_EE4308MSGMASTER_H
